spring:
  application:
    name: 'usuario_service'
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/taskfinal_v2
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWD:baal}
    driverClassName: org.postgresql.Driver

server:
  port: 9091
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/